### ISSUE TITLE
service api and how to call it to interference

### ISSUE THREAD

**Issue by wanghaisheng** [cap-ntu/ML-Model-CI#168]
could not find any doc about this topic

**Comment by HuaizhengZhang** [comment]
> could not find any doc about this topic

Hi, thanks for your star and interest. The current doc does not cover all details due to the short-handed. The code is here
https://github.com/cap-ntu/ML-Model-CI/blob/ce0cdb2182ee2da4fc799cada8659a8c2f6dd673/modelci/controller/controller.py#L41

The project is still under active development. We will present a completed document after it is stale.

**Comment by wanghaisheng** [comment]
since it is under active development , suggest take a look at  and learn from this  More industrial project
https://github.com/flipkart-incubator/Hunch

**Comment by HuaizhengZhang** [comment]
Thanks for your suggestions. Will do.
